### ISSUE TITLE
Build fails after upgrade on December 7th.

### ISSUE THREAD

**Issue by gberlotperalta** [fralau/mkdocs_macros_plugin#18]
After the upgrade, we can build sites using your plugin, see the error below (extract from jenkins):

[32m[macros] Macros arguments:[0m {'module_name': 'main', 'include_yaml': []}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/macros/plugin.py", line 214, in _load_module
    module = importlib.import_module(python_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python3.7/site-packages/mkdocs/commands/build.py", line 240, in build
    config = config['plugins'].run_event('config', config)
  File "/usr/local/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/macros/plugin.py", line 261, in on_config
    self._load_module()
  File "/usr/local/lib/python3.7/site-packages/macros/plugin.py", line 234, in _load_module
    (python_module, self.project_dir))
ImportError: Macro plugin could not find custom 'main' module in '/home/ubuntu/workspace/et_previous_version_macro_plugin'.

**Note;** we reverted back to the previous version and worked.

**Comment by fralau** [comment]
In principle it is 1 for 1 compatibile. At what point did you get the above errors? While installing the package? Or when running the `mkdocs build` command?
