### ISSUE TITLE
When starting mkdocs serve, the following error:

### ISSUE THREAD

**Issue by oleksandr-zh** [fralau/mkdocs_macros_plugin#26]
mkdocs serve
mkdocs : INFO    -  Building documentation... 
At line:1 char:1
+ mkdocs serve
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (INFO    -  Building documentation... :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "C:\Python38\Scripts\mkdocs-script.py", line 11, in <module>
    load_entry_point('mkdocs==1.1', 'console_scripts', 'mkdocs')()
  File "C:\Python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mkdocs\__main__.py", line 140, in serve_command
    serve.serve(
  File "C:\Python38\lib\site-packages\mkdocs\commands\serve.py", line 141, in serve
    config = builder()
  File "C:\Python38\lib\site-packages\mkdocs\commands\serve.py", line 122, in builder
    config = load_config(
  File "C:\Python38\lib\site-packages\mkdocs\config\base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "C:\Python38\lib\site-packages\mkdocs\config\base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "C:\Python38\lib\site-packages\mkdocs\config\base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "C:\Python38\lib\site-packages\mkdocs\config\config_options.py", line 130, in validate
    return self.run_validation(value)
  File "C:\Python38\lib\site-packages\mkdocs\config\config_options.py", line 591, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "C:\Python38\lib\site-packages\mkdocs\config\config_options.py", line 599, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "C:\Python38\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python38\lib\site-packages\macros\plugin.py", line 19, in <module>
    from mkdocs.utils import string_types
ImportError: cannot import name 'string_types' from 'mkdocs.utils' (C:\Python38\lib\site-packages\mkdocs\utils\__init
__.py)
![mkdocs-err](https://user-images.githubusercontent.com/50334048/76074874-b5f18100-5fa4-11ea-9399-91e4f6e8b03a.jpg)

**Comment by fralau** [comment]
This is a duplicate issue of #24. This should be fixed: update mkdocs-mcros-plugin (from github, as pypi is not updated yet).

**Comment by fralau** [comment]
Pypi is updated with 0.4.4. Did this solve your question?

**Comment by oleksandr-zh** [comment]
Yes, its work!
