### ISSUE TITLE
mkdocs_macros_plugin does not run with Python 3.6

### ISSUE THREAD

**Issue by czenker** [fralau/mkdocs_macros_plugin#28]
I experienced this issue when running `mkdocs build` with Python `3.6.10` on travis-ci ([full log](https://travis-ci.org/github/wifi-tally/wifi-tally/builds/663660054#L434)). The exception is:

````bash
$ mkdocs build
[macros] Macros arguments: {'module_name': 'main', 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': ''}
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.10/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/mkdocs/commands/build.py", line 239, in build
    config = config['plugins'].run_event('config', config)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/macros/plugin.py", line 309, in on_config
    define_env(self)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/macros/context.py", line 235, in define_env
    env.variables['git'] = get_git_info()
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/macros/context.py", line 146, in get_git_info
    text=True).strip()
  File "/opt/python/3.6.10/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/python/3.6.10/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
The command "mkdocs build" exited with 1.
````
According to [the docs](https://docs.python.org/3.6/library/subprocess.html#subprocess.run) the `text` argument does not exist in 3.6.

I am not sure if this needs fixing, but the communicated requirements for the plugin are Python >= 3.5.

**Comment by nihilismus** [comment]
Facing the same issue with Python `3.6.9`.

**Comment by fralau** [comment]
Thanks for the heads up.

**Comment by fralau** [comment]
Fixed in d273936 (0.4.6). Could you let me know whether it worked for you?

**Comment by nihilismus** [comment]
@fralau thanks, it works for me in Python `3.6.9` and `3.8.0`.

**Comment by fralau** [comment]
Thanks a lot for your contribution! Happy production of documentation :-)
